/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as InvoicingRouteImport } from './routes/invoicing'
import { Route as HelpdeskRouteImport } from './routes/helpdesk'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppBillingRouteImport } from './routes/app/billing'

const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicingRoute = InvoicingRouteImport.update({
  id: '/invoicing',
  path: '/invoicing',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpdeskRoute = HelpdeskRouteImport.update({
  id: '/helpdesk',
  path: '/helpdesk',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/app/billing',
  path: '/app/billing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm': typeof CrmRoute
  '/helpdesk': typeof HelpdeskRoute
  '/invoicing': typeof InvoicingRoute
  '/projects': typeof ProjectsRoute
  '/queue': typeof QueueRoute
  '/app/billing': typeof AppBillingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crm': typeof CrmRoute
  '/helpdesk': typeof HelpdeskRoute
  '/invoicing': typeof InvoicingRoute
  '/projects': typeof ProjectsRoute
  '/queue': typeof QueueRoute
  '/app/billing': typeof AppBillingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crm': typeof CrmRoute
  '/helpdesk': typeof HelpdeskRoute
  '/invoicing': typeof InvoicingRoute
  '/projects': typeof ProjectsRoute
  '/queue': typeof QueueRoute
  '/app/billing': typeof AppBillingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crm'
    | '/helpdesk'
    | '/invoicing'
    | '/projects'
    | '/queue'
    | '/app/billing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crm'
    | '/helpdesk'
    | '/invoicing'
    | '/projects'
    | '/queue'
    | '/app/billing'
  id:
    | '__root__'
    | '/'
    | '/crm'
    | '/helpdesk'
    | '/invoicing'
    | '/projects'
    | '/queue'
    | '/app/billing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrmRoute: typeof CrmRoute
  HelpdeskRoute: typeof HelpdeskRoute
  InvoicingRoute: typeof InvoicingRoute
  ProjectsRoute: typeof ProjectsRoute
  QueueRoute: typeof QueueRoute
  AppBillingRoute: typeof AppBillingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoicing': {
      id: '/invoicing'
      path: '/invoicing'
      fullPath: '/invoicing'
      preLoaderRoute: typeof InvoicingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpdesk': {
      id: '/helpdesk'
      path: '/helpdesk'
      fullPath: '/helpdesk'
      preLoaderRoute: typeof HelpdeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/app/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrmRoute: CrmRoute,
  HelpdeskRoute: HelpdeskRoute,
  InvoicingRoute: InvoicingRoute,
  ProjectsRoute: ProjectsRoute,
  QueueRoute: QueueRoute,
  AppBillingRoute: AppBillingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
